
package administracionescolar;


public class CalculoPromedioGeneral extends javax.swing.JFrame {

int i=0;

    public CalculoPromedioGeneral() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        campoCurso = new javax.swing.JComboBox();
        campoMateria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        campoPGM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoPG = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Promedio Genaral y Promedio General por Materia");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Curso");

        jLabel5.setText("Materia");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        campoCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        campoMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matemática", "Lengua", "Física", "Química", "Biología", "Ética", "Historia", "Geografía", "Computación" }));

        jLabel6.setText("PGM ");

        jLabel7.setText("PG");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel8.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(196, 196, 196))
                                    .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(campoMateria, 0, 270, Short.MAX_VALUE)
                                        .addGap(50, 50, 50))))
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(campoPGM, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(campoPG, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Calcular)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoPGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campoPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed

}//GEN-LAST:event_campoNombreActionPerformed

private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed

}//GEN-LAST:event_campoApellidoActionPerformed

private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed

    boolean encontro=false;
    //BUSCA EL ALUMNO EN LA CORRESPONDIENTE LISTA Y CALCULA LOS PROMEDIOS...
    switch (campoCurso.getSelectedIndex()+1){
    case 1:
         for (i=0; i<AdministracionEscolar.listaAlumnos1.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos1.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos1.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos1.get(i)
                        .calcularPromedioGeneral()));
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        encontro= true;
                }
                   
}
         if (!encontro){
                    new Error().setVisible(true);
                }
                 
        break;
    case 2:
         for (i=0; i<AdministracionEscolar.listaAlumnos2.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos2.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos2.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos2.get(i)
                        .calcularPromedioGeneral()));
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        encontro=true;
                }   
}
         if (!encontro){
                    new Error().setVisible(true);
                }
                 
        break;    
    case 3:
         for (i=0; i<AdministracionEscolar.listaAlumnos3.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos3.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos3.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos3.get(i)
                        .calcularPromedioGeneral()));
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        encontro=true;
                }
                }
         if (!encontro){
                    new Error().setVisible(true);
                }
                
        break;
    case 4:
         for (i=0; i<AdministracionEscolar.listaAlumnos4.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos4.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos4.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos4.get(i)
                        .calcularPromedioGeneral()));
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        encontro=true;
                }
                }
         if (!encontro){
                    new Error().setVisible(true);
                }
                
        break;
    case 5:
         for (i=0; i<AdministracionEscolar.listaAlumnos5.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos5.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos5.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos5.get(i)
                        .calcularPromedioGeneral()));
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        encontro=true;
                }
                }
         if (!encontro){
                    new Error().setVisible(true);
                }
                
        break;
    case 6:
         for (i=0; i<AdministracionEscolar.listaAlumnos6.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos6.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos6.get(i).getApellido().equals(campoApellido.getText()))){
                        campoPGM.setText(Float.toString(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[
                        campoMateria.getSelectedIndex()].calculaPromedioPorMateria()));
                        campoPG.setText(Float.toString(AdministracionEscolar.listaAlumnos6.get(i)
                        .calcularPromedioGeneral()));
                        encontro=true;
                }
                }
         if (!encontro){
                    new Error().setVisible(true);
                }
                
        break;
}
}//GEN-LAST:event_CalcularActionPerformed

private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();
}//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoPromedioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoPromedioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoPromedioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoPromedioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CalculoPromedioGeneral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JComboBox campoCurso;
    private javax.swing.JComboBox campoMateria;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPG;
    private javax.swing.JTextField campoPGM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
