
package administracionescolar;

import java.io.*;

public class IngresarAlumnoPorArchivo extends javax.swing.JFrame {

    String nombreArchivo, nombre, apellido, dni, concepto;
    int curso, inasistencias;
    public IngresarAlumnoPorArchivo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombreArchivo = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cargar Por Archivo Los Alumnos");

        jLabel2.setText("Ingrese el path del archivo");

        campoNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreArchivoActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(campoNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(campoNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void campoNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreArchivoActionPerformed

}//GEN-LAST:event_campoNombreArchivoActionPerformed

private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
                        try{
                        File archivo= new File(campoNombreArchivo.getText());
                        FileReader leo = null;
                        leo = new FileReader(archivo);
                        
                        BufferedReader lector= new BufferedReader(leo);
                        while((nombre=lector.readLine())!=null){
                         apellido= lector.readLine();
                         dni= lector.readLine();
                         curso= Integer.parseInt(lector.readLine());
                         inasistencias= Integer.parseInt(lector.readLine());
                         concepto= lector.readLine();
                         //GUARDA LA INFORMACION DEL ARCHIVO EN EL OBJETO "alumnoAuxiliar".......
                         Alumno alumnoAuxiliar= new Alumno(nombre, apellido, dni, curso, inasistencias, concepto);
                        
                        
                        //GUARDA EL OBJETO EN LA LISTA CORRESPONDIENTE DE ACUERDO AL CURSO DEL ALUMNO
    switch (curso) {
        case 1:
            if (AdministracionEscolar.listaAlumnos1.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos1.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
        case 2:
            if (AdministracionEscolar.listaAlumnos2.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos2.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
        case 3:
            if (AdministracionEscolar.listaAlumnos3.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos3.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
        case 4:
            if (AdministracionEscolar.listaAlumnos4.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos4.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
        case 5:
            if (AdministracionEscolar.listaAlumnos5.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos5.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
        case 6:
            if (AdministracionEscolar.listaAlumnos6.size()>32){
                new Error().setVisible(true);
            }
            else{
            AdministracionEscolar.listaAlumnos6.add(alumnoAuxiliar);
            new AccionRealizada().setVisible(true);
            }
            break;
            
    }
                        }
                        leo.close();
                        lector.close();
                        }
                        catch(IOException e){
                           new Error().setVisible(true);
                        }
}//GEN-LAST:event_aceptarActionPerformed

private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
dispose();
}//GEN-LAST:event_cancelarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumnoPorArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumnoPorArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumnoPorArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumnoPorArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IngresarAlumnoPorArchivo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField campoNombreArchivo;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
