/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarNotasdeAlumno.java
 *
 * Created on 11/11/2012, 03:52:20
 */
package administracionescolar;


public class ModificarNotasdeAlumno extends javax.swing.JFrame {

    public ModificarNotasdeAlumno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBox1Cuatrimestre = new javax.swing.JComboBox();
        comboBox2Cuatrimestre = new javax.swing.JComboBox();
        comboBox3Cuatrimestre = new javax.swing.JComboBox();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboBoxCurso = new javax.swing.JComboBox();
        comboBoxMateria = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificar las notas de un alumno");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Materia");

        jLabel5.setText("1 Cuatrimestre");

        jLabel6.setText("2 Cuatrimestre");

        jLabel7.setText("3 Cuatrimestre");

        comboBox1Cuatrimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboBox2Cuatrimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboBox3Cuatrimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Curso");

        comboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        comboBoxMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matemática", "Lengua", "Física", "Química", "Biología", "Ética", "Historia", "Geografía", "Computación" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBox1Cuatrimestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(49, 49, 49)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(comboBox2Cuatrimestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(49, 49, 49))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(comboBox3Cuatrimestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addGap(82, 82, 82)
                                .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxMateria, 0, 230, Short.MAX_VALUE)
                                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addComponent(comboBoxCurso, 0, 230, Short.MAX_VALUE))))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoApellido))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxCurso))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxMateria))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox1Cuatrimestre)
                    .addComponent(comboBox3Cuatrimestre)
                    .addComponent(comboBox2Cuatrimestre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed

}//GEN-LAST:event_campoNombreActionPerformed

private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed

}//GEN-LAST:event_campoApellidoActionPerformed

private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    int i;
    boolean encontro=false;
    switch(comboBoxCurso.getSelectedIndex()+1){
        
        //BUSCA EL ALUMNO EN LA CORRESPONDIENTE LISTA Y MODIFICA LAS NOTAS........

        case 1:
            for (i=0; i<AdministracionEscolar.listaAlumnos1.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos1.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos1.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
                }
            }
                        if (!encontro) {
            new Error().setVisible(true);
                }
            break;
        case 2:
            for (i=0; i<AdministracionEscolar.listaAlumnos2.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos2.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos2.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
            }
            }
                        if (!encontro) {
            new Error().setVisible(true);
    }
            break;
        case 3:
            for (i=0; i<AdministracionEscolar.listaAlumnos3.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos3.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos3.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
            }
            }
                        if (!encontro) {
            new Error().setVisible(true);
    }
            break;
        case 4:
            for (i=0; i<AdministracionEscolar.listaAlumnos4.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos4.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos4.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
            }
            }
                        if (!encontro) {
            new Error().setVisible(true);
    }
            break;
        case 5:
            for (i=0; i<AdministracionEscolar.listaAlumnos5.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos5.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos5.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
            }
            }
                        if (!encontro) {
            new Error().setVisible(true);
    }
            break;
        case 6:
            for (i=0; i<AdministracionEscolar.listaAlumnos6.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos6.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos6.get(i).getApellido().equals(campoApellido.getText()))){
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota1(comboBox1Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota2(comboBox2Cuatrimestre.getSelectedIndex()+1);
                        AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[(comboBoxMateria.
                        getSelectedIndex())].setNota3(comboBox3Cuatrimestre.getSelectedIndex()+1);
                        new AccionRealizada().setVisible(true);
                        encontro=true;
            }
            }
                        if (!encontro) {
            new Error().setVisible(true);
    }
            break;
        }
}//GEN-LAST:event_AceptarActionPerformed

private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
dispose();
}//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarNotasdeAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarNotasdeAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarNotasdeAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarNotasdeAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModificarNotasdeAlumno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox comboBox1Cuatrimestre;
    private javax.swing.JComboBox comboBox2Cuatrimestre;
    private javax.swing.JComboBox comboBox3Cuatrimestre;
    private javax.swing.JComboBox comboBoxCurso;
    private javax.swing.JComboBox comboBoxMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
