
package administracionescolar;

public class MostrarLibretaAlumno extends javax.swing.JFrame {

int i;
boolean encontro;
    public MostrarLibretaAlumno() {
        initComponents();
        matematica.setEditable(false);
        lengua.setEditable(false);
        fisica.setEditable(false);
        quimica.setEditable(false);
        biologia.setEditable(false);
        etica.setEditable(false);
        historia.setEditable(false);
        geografia.setEditable(false);
        computacion.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        comboCurso = new javax.swing.JComboBox();
        Aceptar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quimica = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lengua = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        matematica = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        biologia = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        etica = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        fisica = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        geografia = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        computacion = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        historia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Libreta del alumno");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Curso");

        comboCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        quimica.setColumns(20);
        quimica.setRows(5);
        jScrollPane1.setViewportView(quimica);

        lengua.setColumns(20);
        lengua.setRows(5);
        jScrollPane2.setViewportView(lengua);

        matematica.setColumns(20);
        matematica.setRows(5);
        jScrollPane3.setViewportView(matematica);

        biologia.setColumns(20);
        biologia.setRows(5);
        jScrollPane4.setViewportView(biologia);

        etica.setColumns(20);
        etica.setRows(5);
        jScrollPane5.setViewportView(etica);

        fisica.setColumns(20);
        fisica.setRows(5);
        jScrollPane6.setViewportView(fisica);

        geografia.setColumns(20);
        geografia.setRows(5);
        jScrollPane7.setViewportView(geografia);

        computacion.setColumns(20);
        computacion.setRows(5);
        jScrollPane8.setViewportView(computacion);

        historia.setColumns(20);
        historia.setRows(5);
        jScrollPane9.setViewportView(historia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(campoNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Aceptar)
                                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(Salir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Salir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane8))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    encontro= false;
    switch (comboCurso.getSelectedIndex()+1){
    case 1:
         for (i=0; i<AdministracionEscolar.listaAlumnos1.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos1.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos1.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos1.get(i).materiasCursa[8].toString());
                        encontro=true;
                        
                }
            }
                if (!encontro){
                    new Error().setVisible(true);
                }
                    
        break;
    case 2:
         for (i=0; i<AdministracionEscolar.listaAlumnos2.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos2.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos2.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos2.get(i).materiasCursa[8].toString());
                        encontro=true;
                }
            }
                if (!encontro){
                    new Error().setVisible(true);
                }
                    
        break;    
    case 3:
         for (i=0; i<AdministracionEscolar.listaAlumnos3.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos3.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos3.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos3.get(i).materiasCursa[8].toString());
                        encontro=true;
                }
            }
                if (!encontro){
                    new Error().setVisible(true);
                }
                    
        break;
      case 4:
         for (i=0; i<AdministracionEscolar.listaAlumnos4.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos4.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos4.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos4.get(i).materiasCursa[8].toString());
                        encontro=true;
                }
                }
          if (!encontro) {
                    new Error().setVisible(true);
                }
                    

        break;
case 5:
         for (i=0; i<AdministracionEscolar.listaAlumnos5.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos5.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos5.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos5.get(i).materiasCursa[8].toString());
                        encontro=true;
                }
         }
                if (!encontro){
                    new Error().setVisible(true);
                }
                    
        break;
case 6:
         for (i=0; i<AdministracionEscolar.listaAlumnos6.size(); i++) {
                if ((AdministracionEscolar.listaAlumnos6.get(i).getNombre().equals(campoNombre.getText()))&&
                   (AdministracionEscolar.listaAlumnos6.get(i).getApellido().equals(campoApellido.getText()))){
                        matematica.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[0].toString());
                        lengua.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[1].toString());
                        fisica.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[2].toString());
                        quimica.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[3].toString());
                        biologia.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[4].toString());
                        etica.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[5].toString());
                        historia.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[6].toString());
                        geografia.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[7].toString());
                        computacion.setText(AdministracionEscolar.listaAlumnos6.get(i).materiasCursa[8].toString());
                        encontro=true;
                }
            }
                if (!encontro){
                    new Error().setVisible(true);
                }
                    
        break;
}
}//GEN-LAST:event_AceptarActionPerformed

private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
dispose();
}//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarLibretaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarLibretaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarLibretaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarLibretaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MostrarLibretaAlumno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextArea biologia;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JTextArea computacion;
    private javax.swing.JTextArea etica;
    private javax.swing.JTextArea fisica;
    private javax.swing.JTextArea geografia;
    private javax.swing.JTextArea historia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea lengua;
    private javax.swing.JTextArea matematica;
    private javax.swing.JTextArea quimica;
    // End of variables declaration//GEN-END:variables
}
